apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sparkapp
  namespace: argocd
spec:
  destination:
    namespace: sparkapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sparkapp
    repoURL: https://github.com/uniuuu/sparkargocd.git
#    targetRevision: 0.0.1
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      replace: true
        #      selfHeal: true
      RespectIgnoreDifferences: true
        #  ignoreDifferences:
        #     - group: apps
        #       namespace: sparkapp
        #       kind: Pod
        #       jsonPointers:
        #         - /metadata
        #     - group: apiextensions.k8s.io
        #       name: trafficsplits.split.smi-spec.io
        #       kind: CustomResourceDefinition
        #       jsonPointers:
        #         - /spec/preserveUnknownFields

