apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-app
  namespace: default
    #  namespace: sparkapp
spec:
  type: Scala
  mode: cluster
    #  image: "localhost:32000/spark-operator/spark:v3.1.1"
  image: uniuuu/sparkapp:0.0.11
  imagePullPolicy: Always
    #  mainClass: org.apache.spark.examples.SparkPi
  mainClass: org.apache.spark.eks.assembly.SparkApp
    #  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  mainApplicationFile: "local:///opt/spark/jars/spark-eks-assembly-3.1.2.jar"
    #  sparkVersion: "3.1.1"
  sparkVersion: "3.1.2"
  restartPolicy:
    type: Never
      #   type: Always
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.2
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
