name: Spark App

on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - spark-application/**
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v4
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUBUSERNAME }}
              password: ${{ secrets.DOCKERHUBTOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: ./spark-application
              push: true
              tags: uniuuu/sparkapp:0.0.${{ github.run_number }}
  newversion:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: change version
        run: |
          sed -i "s+uniuuu/sparkapp.*+uniuuu/sparkapp:0.0.$RUN_NUMBER+g" sparkapp/spark-application.yaml
          git add .
          git commit -m 'Github Actions Update Image Version: ${{ github.run_number }}'
          git push origin main
        env:
          RUN_NUMBER: ${{ github.run_number }}
